services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  In2code\In2frontendauthentication\:
    resource: '../Classes/*'

  In2code\In2frontendauthentication\EventListener\ModifyFeGroups:
    tags:
      - name: event.listener
        identifier: 'modifyFeGroupsListener'
        event: TYPO3\CMS\Frontend\Authentication\ModifyResolvedFrontendGroupsEvent

  In2code\In2frontendauthentication\EventListener\AddCustomGroups:
    tags:
      - name: event.listener
        identifier: 'addCustomGroupsEventListener'
        after: modifyFeGroupsListener
        event: BeechIt\FalSecuredownload\Events\AddCustomGroupsEvent
